eleven-labs/github

- repositories.tf
~~:warning: depend: pull request #11 should be merged before this one~~
> feat(tf): update github repository configuration

- repositories.tf
~~:warning: depend: resources should be imported into terraform state before merging the pull request~~
> feat(tf): import blog.eleven-labs.com repository

- repositories.tf
~~:warning: depend: pull request #14 should be merged first~~
> feat(tf): import codelabs repository

- module/team/main.tf
- module/team/variables.tf
- teams.tf
~⚠️depend: teams and memberships should be imported manually before merge~
Avoid destroy and recreate when moving teams memberships
> refactor(tf,team): use for-each to compute teams memberships

- teams.tf
- users.tf
- Add `ThibautAlgrin` as a `member` of the `eleven-labs` organization _(manually imported)_
- Add `ThibautAlgrin` as a `member` of the `developers` team _(manually imported)_
~
> feat(user,team): add thibaut algrin

- teams.tf
- users.tf
- Add `mikaben89` as a `member` of the `eleven-labs` organization
- Add `mikaben89` as a `member` of the `developers` team
~
> feat(user,team): add michael benaim

- repositories.tf
- remove implicit `restriction` for `arnaud veber` on `blog.eleven-labs.com` repository
- remove implicit `reviews dismissal` for `core` team on `github` repository 
~
> chore(repository): remove useless config

- teams.tf
- users.tf
Remove organization and team membership for VERMEIL Pierre
~
> feat(user,team): remove pierre vermeil

- teams.tf
- users.tf
- Add `FireWolfHound ` as a `member` of the `eleven-labs` organization
- Add `FireWolfHound ` as a `member` of the `developers` team
~
> feat(user,team): add yuval abudarham

- teams.tf
- users.tf
Please explain the changes you made here and link to any relevant issues.
Please list all the breaking changes introduced by your changes.
> feat(user,team) : add allier alexandre

- repositories.tf
- teams.tf
> feat(repositories): Add Planets repository

- .travis.yml
- README.md
- terraform.tf
Upgrade of terraform required after manual change
~
> fix(ci): upgrade terraform version

- users.tf
Change PIERLOTRomain user-name `GusTTShowbiz` -> `rpierlot`
~
> feat(tf,users): change PIERLOTRomain user-name

- users.tf
change victor delpeyroux username
~
> feat(tf,users): change victor delpeyroux username

- users.tf
Change michael benaim username
~
> feat(tf,users): change michael benaim username

- repositories.tf
Require terraform check on `github` repository
~
> feat(tf,repo): require terraform check on github repository

- README.md
> fix(readme): badge url

- repositories.tf
- teams.tf
track amp-jekyll repo
set teams permissions on this repo
~
> add repo amp-jekyll

- teams.tf
- users.tf
- remove user `ABUDARHAMYuval`
- remove `ABUDARHAMYuval` from `Developer` team
~
> chore(user,team): remove user ABUDARHAM Yuval

- teams.tf
- users.tf
- add user `VERNEUILFlorian`
- add `VERNEUILFlorian` to `Developer` team
~
> chore(user,team): add developer florian verneuil

- users.tf
Update FEIRESEN Benjamin username
~
> chore(user): update feiresen benjamin username
